const sampleData = {
  products: [
    {
      name: 'Signature Luxe White Dress Shirt',
      slug: 'signature-luxe-white-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'Crafted from premium 100% long-staple cotton, this double-ply signature shirt offers unparalleled durability and an exceptionally soft finish. It features a modern cutaway collar, double-button mitred cuffs, and a smooth French placket. Perfect for board meetings or high-profile events.',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 2499,
      brand: 'ThreadNova Luxe',
      rating: 4.8,
      numReviews: 24,
      stock: 15,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'Chelsea Herringbone Formal Shirt',
      slug: 'chelsea-herringbone-formal-shirt',
      category: "Men's Dress Shirts",
      description: 'A classic fit dress shirt distinguished by a subtle herringbone texture that adds depth and sophistication. Styled with an elegant spread collar and single-cuff setup, it is easily accessorized with a silk tie or worn open for a refined business-casual look.',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 1899,
      brand: 'Brooks Brothers',
      rating: 4.5,
      numReviews: 14,
      stock: 8,
      isFeatured: true,
      banner: 'banner-2.jpg',
    },
    {
      name: 'Oxford Cambridge Striped Shirt',
      slug: 'oxford-cambridge-striped-shirt',
      category: "Men's Dress Shirts",
      description: 'Perfect for daily office wear, this classic-fit vertical striped shirt is designed with breathable performance stretch weave to keep you fresh and moving freely all day. Includes a button-down collar and chest pocket.',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 1999,
      brand: 'Polo Ralph Lauren',
      rating: 4.3,
      numReviews: 9,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Urban Denim Utility Jacket',
      slug: 'urban-denim-utility-jacket',
      category: "Men's Sweatshirts",
      description: 'Made from heavyweight raw denim, this jacket features triple-stitched seams, classic brass hardware, and dual buttoned chest pockets. It adds a rugged yet clean layer to any outfit and develops a beautiful custom patina over time.',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 3499,
      brand: 'Levis',
      rating: 4.7,
      numReviews: 32,
      stock: 6,
      isFeatured: true,
      banner: 'promo.jpg',
    },
    {
      name: 'Essential Heavyweight Oversized Hoodie',
      slug: 'essential-heavyweight-oversized-hoodie',
      category: "Men's Sweatshirts",
      description: 'Relax in ultimate comfort. Featuring a thick 450 GSM organic cotton blend loopback fleece, custom drop-shoulder silhouette, and double-lined hood. Ideal for cooler weather and casual weekend wear.',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 2199,
      brand: 'ThreadNova Basics',
      rating: 4.9,
      numReviews: 45,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Classic Heather Crewneck Sweatshirt',
      slug: 'classic-heather-crewneck-sweatshirt',
      category: "Men's Sweatshirts",
      description: 'Designed for versatility and longevity. Made from soft French terry fabric with ribbed side panels, cuffs, and hem. Pairs seamlessly with denim or chinos for an effortless collegiate look.',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 1599,
      brand: 'Tommy Hilfiger',
      rating: 4.4,
      numReviews: 18,
      stock: 14,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Signature Minimalist White Watch',
      slug: 'signature-minimalist-white-watch',
      category: 'Accessories',
      description: 'Keep track of time with clean sophistication. This minimalist watch features a scratch-resistant sapphire crystal glass, a white enamel dial with silver markers, and an ultra-thin stainless steel mesh strap.',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 4599,
      brand: 'Daniel Wellington',
      rating: 4.6,
      numReviews: 29,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Classic Cognac Leather Strap Watch',
      slug: 'classic-cognac-leather-strap-watch',
      category: 'Accessories',
      description: 'Elegant craftsmanship meets rugged design. Powered by a Japanese quartz movement, this watch is completed with an analog date window, brushed gunmetal case, and a genuine full-grain cognac leather strap.',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 5299,
      brand: 'Fossil',
      rating: 4.8,
      numReviews: 12,
      stock: 5,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polarized Aviator Sunglasses',
      slug: 'polarized-aviator-sunglasses',
      category: 'Accessories',
      description: 'Protect your eyes in retro style. Made with lightweight gold-toned metal frames and impact-resistant polarized green lenses that eliminate glare and offer 100% UV protection.',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 2999,
      brand: 'Ray-Ban',
      rating: 4.7,
      numReviews: 38,
      stock: 16,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Handcrafted Pebbled Leather Wallet',
      slug: 'handcrafted-pebbled-leather-wallet',
      category: 'Accessories',
      description: 'A sleek bifold wallet slim enough for front pockets but spacious enough for all your essentials. Featuring 6 card slots, a cash slot, RFID blocking lining, and beautifully finished in rich pebbled calf leather.',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 1499,
      brand: 'Saddleback Leather',
      rating: 4.9,
      numReviews: 54,
      stock: 22,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Graceful Silk Elegance Blouse',
      slug: 'graceful-silk-elegance-blouse',
      category: "Women's Tops",
      description: 'A luxurious silk-crepe blouse that adds sophisticated elegance to your work-to-weekend wardrobe. Features delicate pleating at the neckline, tailored long cuffs, and a fluid silhouette that drapes beautifully.',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 2999,
      brand: 'Zara',
      rating: 4.6,
      numReviews: 21,
      stock: 7,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Everyday Premium Pima Cotton Tee',
      slug: 'everyday-premium-pima-cotton-tee',
      category: "Women's Tops",
      description: 'The search for the perfect basic tee ends here. Crafted from rare, extra-long staple Pima cotton, it features a flattering neckline, fitted sleeves, and is pre-washed to avoid shrinking and preserve shape.',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 999,
      brand: 'H&M Premium',
      rating: 4.2,
      numReviews: 42,
      stock: 30,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Summer Flow Floral Dress',
      slug: 'summer-flow-floral-dress',
      category: "Women's Tops",
      description: 'Perfect for sunny outings. This gorgeous tiered maxi dress features a hand-designed floral motif, adjustable tie-shoulder straps, and is crafted in lightweight linen for optimal summer cooling.',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 3599,
      brand: 'Mango',
      rating: 4.7,
      numReviews: 19,
      stock: 4,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Cozy Wool Cable Knit Sweater',
      slug: 'cozy-wool-cable-knit-sweater',
      category: "Women's Tops",
      description: 'Wrap up in comfort. Blended with ultra-soft Merino wool, this cable knit sweater is complete with a thick ribbed collar, relaxed dropped shoulders, and a warm, heavyweight cozy feel.',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 3299,
      brand: 'Uniqlo U',
      rating: 4.8,
      numReviews: 27,
      stock: 9,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
